# Generated by Django 3.2 on 2024-12-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('openalex_institution_id', models.TextField()),
                ('ror', models.TextField()),
                ('display_name', models.TextField()),
                ('display_name_alternatives', models.JSONField(blank=True, null=True)),
                ('country_code', models.CharField(max_length=10)),
                ('type', models.TextField()),
                ('homepage_url', models.TextField()),
                ('works_count', models.IntegerField()),
                ('cited_by_count', models.IntegerField()),
                ('two_yr_mean_citedness', models.IntegerField(default=0)),
                ('two_yr_works_count', models.IntegerField(default=0)),
                ('two_yr_cited_by_count', models.IntegerField(default=0)),
                ('h_index', models.IntegerField(default=0)),
                ('oa_percent', models.FloatField(default=0)),
                ('wikidata', models.TextField()),
            ],
        ),
    ]
