# Generated by Django 3.2 on 2024-12-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('openalex_paper_id', models.TextField(default='')),
                ('title', models.TextField()),
                ('authorships', models.JSONField(blank=True, null=True)),
                ('institutions', models.JSONField(blank=True, null=True)),
                ('publish_date', models.DateField()),
                ('journal', models.CharField(blank=True, max_length=1250, null=True)),
                ('volume', models.CharField(blank=True, max_length=1250, null=True)),
                ('issue', models.CharField(blank=True, max_length=1250, null=True)),
                ('doi', models.CharField(blank=True, max_length=1250, null=True)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('abstract', models.JSONField()),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('citation_count', models.PositiveIntegerField(default=0)),
                ('download_link', models.CharField(blank=True, max_length=1500, null=True)),
                ('original_link', models.CharField(blank=True, max_length=1500, null=True)),
                ('references_works', models.JSONField(blank=True, null=True)),
                ('research_fields', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('related_works', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
