# Generated by Django 3.2 on 2024-12-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('openalex_topic_id', models.TextField()),
                ('display_name', models.CharField(max_length=255)),
                ('works_count', models.IntegerField(default=0)),
                ('cited_by_count', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('keywords', models.JSONField()),
                ('siblings', models.JSONField()),
                ('topic_papers', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
