# Generated by Django 3.2 on 2024-12-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('openalex_author_id', models.TextField()),
                ('orcid', models.TextField()),
                ('name', models.TextField()),
                ('name_alternatives', models.JSONField(blank=True, null=True)),
                ('works_count', models.IntegerField(default=0)),
                ('cited_by_count', models.IntegerField(default=0)),
                ('h_index', models.IntegerField(default=0)),
                ('two_yr_mean_citedness', models.IntegerField(default=0)),
                ('two_yr_cited_by_count', models.IntegerField(default=0)),
                ('last_known_institutions', models.JSONField(blank=True, null=True)),
                ('topics', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
